updated configure system
git-svn-id: file:///Users/petejw/Documents/libmesh_svn_bak@575 434f946d-2f3d-0410-ba4c-cb9f52fb0dbf

diff --git a/trunk/libmesh/configure b/trunk/libmesh/configure
--- a/trunk/libmesh/configure
+++ b/trunk/libmesh/configure
@@ -7931,12 +7931,82 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_lam_lam_show_version" >&5
 echo "${ECHO_T}$ac_cv_lib_lam_lam_show_version" >&6
 if test $ac_cv_lib_lam_lam_show_version = yes; then
 
-                       LIBS="$LIBS -llam"
+                       LIBS    ="-llam $LIBS"
                        MPI_LIBS="-llam $MPI_LIBS"
                        MPI_IMPL="lam"
 
 fi
 
+
+	# Quadricss MPI requires the elan library to be included too
+	if (nm $MPI_LIBS_PATH/libmpi.a | grep elan > /dev/null); then
+	  echo "note: MPI found to use Quadrics switch, looking for elan library"
+		 echo "$as_me:$LINENO: checking for elan_init in -lelan" >&5
+echo $ECHO_N "checking for elan_init in -lelan... $ECHO_C" >&6
+if test "${ac_cv_lib_elan_elan_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lelan  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char elan_init ();
+int
+main ()
+{
+elan_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_elan_elan_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_elan_elan_init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_elan_elan_init" >&5
+echo "${ECHO_T}$ac_cv_lib_elan_elan_init" >&6
+if test $ac_cv_lib_elan_elan_init = yes; then
+
+                                LIBS    ="-lelan $LIBS"
+                                MPI_LIBS="-lelan $MPI_LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Could not find elan library... exiting " >&5
+echo "$as_me: error: Could not find elan library... exiting " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+	fi
 
 	echo "$as_me:$LINENO: checking for MPI_Init in -lmpi" >&5
 echo $ECHO_N "checking for MPI_Init in -lmpi... $ECHO_C" >&6
@@ -7999,72 +8069,6 @@ if test $ac_cv_lib_mpi_MPI_Init = yes; then
                        echo "$as_me:$LINENO: result: Found valid MPI installlaion..." >&5
 echo "${ECHO_T}Found valid MPI installlaion..." >&6
 
-		       # AlphaServer SCs MPI requires the elan library to be included too
-	 	       if nm $MPI_LIBS_PATH/libmpi.a | grep elan > /dev/null; then
-		         echo "note: MPI found to use Quadrics switch, looking for elan library"
-			 echo "$as_me:$LINENO: checking for elan_init in -lelan" >&5
-echo $ECHO_N "checking for elan_init in -lelan... $ECHO_C" >&6
-if test "${ac_cv_lib_elan_elan_init+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lelan  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char elan_init ();
-int
-main ()
-{
-elan_init ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_elan_elan_init=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_elan_elan_init=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_elan_elan_init" >&5
-echo "${ECHO_T}$ac_cv_lib_elan_elan_init" >&6
-if test $ac_cv_lib_elan_elan_init = yes; then
-  MPI_LIBS="$MPI_LIBS -lelan"
-else
-  { { echo "$as_me:$LINENO: error: Could not find elan library... exiting " >&5
-echo "$as_me: error: Could not find elan library... exiting " >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-	               fi
 
 else
   echo "$as_me:$LINENO: result: Could not link in the MPI library..." >&5
@@ -8097,6 +8101,76 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 	LIBS="-L$MPI_LIBS_PATH $LIBS"
+
+	# Quadrics MPICH requires the gm library to be included too
+	if (nm $MPI_LIBS_PATH/libmpich.a | grep gm_open > /dev/null); then
+	  echo "note: MPICH found to use Myricomm's Myrinet, looking for gm library"
+		 echo "$as_me:$LINENO: checking for gm_open in -lgm" >&5
+echo $ECHO_N "checking for gm_open in -lgm... $ECHO_C" >&6
+if test "${ac_cv_lib_gm_gm_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgm  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gm_open ();
+int
+main ()
+{
+gm_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gm_gm_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gm_gm_open=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gm_gm_open" >&5
+echo "${ECHO_T}$ac_cv_lib_gm_gm_open" >&6
+if test $ac_cv_lib_gm_gm_open = yes; then
+
+                                LIBS    ="-lgm $LIBS"
+                                MPI_LIBS="-lgm $MPI_LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Could not find gm library... exiting " >&5
+echo "$as_me: error: Could not find gm library... exiting " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+	fi
 
 	# look for MPI_Init in libmpich.(a/so)
 	echo "$as_me:$LINENO: checking for MPI_Init in -lmpich" >&5
@@ -8521,12 +8595,82 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_lam_lam_show_version" >&5
 echo "${ECHO_T}$ac_cv_lib_lam_lam_show_version" >&6
 if test $ac_cv_lib_lam_lam_show_version = yes; then
 
-                       LIBS="$LIBS -llam"
+                       LIBS    ="-llam $LIBS"
                        MPI_LIBS="-llam $MPI_LIBS"
                        MPI_IMPL="lam"
 
 fi
 
+
+	# Quadricss MPI requires the elan library to be included too
+	if (nm $MPI_LIBS_PATH/libmpi.a | grep elan > /dev/null); then
+	  echo "note: MPI found to use Quadrics switch, looking for elan library"
+		 echo "$as_me:$LINENO: checking for elan_init in -lelan" >&5
+echo $ECHO_N "checking for elan_init in -lelan... $ECHO_C" >&6
+if test "${ac_cv_lib_elan_elan_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lelan  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char elan_init ();
+int
+main ()
+{
+elan_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_elan_elan_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_elan_elan_init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_elan_elan_init" >&5
+echo "${ECHO_T}$ac_cv_lib_elan_elan_init" >&6
+if test $ac_cv_lib_elan_elan_init = yes; then
+
+                                LIBS    ="-lelan $LIBS"
+                                MPI_LIBS="-lelan $MPI_LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Could not find elan library... exiting " >&5
+echo "$as_me: error: Could not find elan library... exiting " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+	fi
 
 	echo "$as_me:$LINENO: checking for MPI_Init in -lmpi" >&5
 echo $ECHO_N "checking for MPI_Init in -lmpi... $ECHO_C" >&6
@@ -8589,72 +8733,6 @@ if test $ac_cv_lib_mpi_MPI_Init = yes; then
                        echo "$as_me:$LINENO: result: Found valid MPI installlaion..." >&5
 echo "${ECHO_T}Found valid MPI installlaion..." >&6
 
-		       # AlphaServer SCs MPI requires the elan library to be included too
-	 	       if nm $MPI_LIBS_PATH/libmpi.a | grep elan > /dev/null; then
-		         echo "note: MPI found to use Quadrics switch, looking for elan library"
-			 echo "$as_me:$LINENO: checking for elan_init in -lelan" >&5
-echo $ECHO_N "checking for elan_init in -lelan... $ECHO_C" >&6
-if test "${ac_cv_lib_elan_elan_init+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lelan  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char elan_init ();
-int
-main ()
-{
-elan_init ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_elan_elan_init=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_elan_elan_init=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_elan_elan_init" >&5
-echo "${ECHO_T}$ac_cv_lib_elan_elan_init" >&6
-if test $ac_cv_lib_elan_elan_init = yes; then
-  MPI_LIBS="$MPI_LIBS -lelan"
-else
-  { { echo "$as_me:$LINENO: error: Could not find elan library... exiting " >&5
-echo "$as_me: error: Could not find elan library... exiting " >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-	               fi
 
 else
   echo "$as_me:$LINENO: result: Could not link in the MPI library..." >&5
@@ -8687,6 +8765,76 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 	LIBS="-L$MPI_LIBS_PATH $LIBS"
+
+	# Quadrics MPICH requires the gm library to be included too
+	if (nm $MPI_LIBS_PATH/libmpich.a | grep gm_open > /dev/null); then
+	  echo "note: MPICH found to use Myricomm's Myrinet, looking for gm library"
+		 echo "$as_me:$LINENO: checking for gm_open in -lgm" >&5
+echo $ECHO_N "checking for gm_open in -lgm... $ECHO_C" >&6
+if test "${ac_cv_lib_gm_gm_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgm  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gm_open ();
+int
+main ()
+{
+gm_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gm_gm_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gm_gm_open=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gm_gm_open" >&5
+echo "${ECHO_T}$ac_cv_lib_gm_gm_open" >&6
+if test $ac_cv_lib_gm_gm_open = yes; then
+
+                                LIBS    ="-lgm $LIBS"
+                                MPI_LIBS="-lgm $MPI_LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Could not find gm library... exiting " >&5
+echo "$as_me: error: Could not find gm library... exiting " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+	fi
 
 	# look for MPI_Init in libmpich.(a/so)
 	echo "$as_me:$LINENO: checking for MPI_Init in -lmpich" >&5
