re-inlined some performance-critical methods in DofObject.  write_gmv() needed an #ifndef ENABLE_INFINITE_ELEMENTS.  Fix for building with --disable-optional.
git-svn-id: file:///Users/petejw/Documents/libmesh_svn_bak@329 434f946d-2f3d-0410-ba4c-cb9f52fb0dbf

diff --git a/trunk/libmesh/configure b/trunk/libmesh/configure
--- a/trunk/libmesh/configure
+++ b/trunk/libmesh/configure
@@ -852,7 +852,6 @@ Optional Features:
   --enable-xdr Set compiler flags to enable xdr binary I/O
   --enable-mgf-workaround Set compiler flags to work around MGF bc problem
   --enable-complex Set compiler flags to build with complex number support
-  --enable-laspack Set compiler flags to build with LASPACK suppport
   --enable-reference-counting build with reference counting suppport
   --enable-perflog build with performance logging turned on
   --enable-hdf4 Set compiler flags to enable HDF4 binary I/O
@@ -862,6 +861,7 @@ Optional Features:
   --enable-metis Set compiler flags to build with Metis suppport
   --enable-sfc Set compiler flags to build with Sfc suppport
   --enable-tecplot build with Tecplot binary support
+  --enable-laspack Set compiler flags to build with LASPACK suppport
   --enable-petsc Set compiler flags to build with Petsc suppport
   --enable-mpi build with MPI message passing support
 
@@ -4439,57 +4439,6 @@ echo "${ECHO_T}<<< Configuring library with real number support >>>" >&6
 fi
 
 
-# Check whether --enable-laspack or --disable-laspack was given.
-if test "${enable_laspack+set}" = set; then
-  enableval="$enable_laspack"
-  enablelaspack=$enableval
-else
-  enablelaspack=yes
-fi;
-
-if test "$enablelaspack" != no ; then
-
-  echo "$as_me:$LINENO: checking for ./contrib/laspack/lastypes.h" >&5
-echo $ECHO_N "checking for ./contrib/laspack/lastypes.h... $ECHO_C" >&6
-if test "${ac_cv_file___contrib_laspack_lastypes_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "./contrib/laspack/lastypes.h"; then
-  ac_cv_file___contrib_laspack_lastypes_h=yes
-else
-  ac_cv_file___contrib_laspack_lastypes_h=no
-fi
-fi
-echo "$as_me:$LINENO: result: $ac_cv_file___contrib_laspack_lastypes_h" >&5
-echo "${ECHO_T}$ac_cv_file___contrib_laspack_lastypes_h" >&6
-if test $ac_cv_file___contrib_laspack_lastypes_h = yes; then
-  LASPACK_INCLUDE_PATH=$PWD/contrib/laspack
-fi
-
-
-  if (test -r $LASPACK_INCLUDE_PATH/lastypes.h) ; then
-
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_LASPACK 1
-_ACEOF
-
-    laspack_version=`grep "define LASPACK_VERSION " $LASPACK_INCLUDE_PATH/version.h | sed -e "s/[^0-9.]*//g"`
-    echo "$as_me:$LINENO: result: <<< Configuring library with LASPACK version $laspack_version support >>>" >&5
-echo "${ECHO_T}<<< Configuring library with LASPACK version $laspack_version support >>>" >&6
-  else
-    enablelaspack=no
-  fi
-
-
-
-fi
-
-
 
 # Check whether --enable-reference-counting or --disable-reference-counting was given.
 if test "${enable_reference_counting+set}" = set; then
@@ -4833,6 +4782,7 @@ echo "${ECHO_T}<<< Configuring library with Metis support >>>" >&6
 fi
 
 
+
 # Check whether --enable-sfc or --disable-sfc was given.
 if test "${enable_sfc+set}" = set; then
   enableval="$enable_sfc"
@@ -5015,6 +4965,58 @@ fi
 
 
 
+# Check whether --enable-laspack or --disable-laspack was given.
+if test "${enable_laspack+set}" = set; then
+  enableval="$enable_laspack"
+  enablelaspack=$enableval
+else
+  enablelaspack=yes
+fi;
+
+if test "$enablelaspack" != no ; then
+
+  echo "$as_me:$LINENO: checking for ./contrib/laspack/lastypes.h" >&5
+echo $ECHO_N "checking for ./contrib/laspack/lastypes.h... $ECHO_C" >&6
+if test "${ac_cv_file___contrib_laspack_lastypes_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./contrib/laspack/lastypes.h"; then
+  ac_cv_file___contrib_laspack_lastypes_h=yes
+else
+  ac_cv_file___contrib_laspack_lastypes_h=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file___contrib_laspack_lastypes_h" >&5
+echo "${ECHO_T}$ac_cv_file___contrib_laspack_lastypes_h" >&6
+if test $ac_cv_file___contrib_laspack_lastypes_h = yes; then
+  LASPACK_INCLUDE_PATH=$PWD/contrib/laspack
+fi
+
+
+  if (test -r $LASPACK_INCLUDE_PATH/lastypes.h) ; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LASPACK 1
+_ACEOF
+
+    laspack_version=`grep "define LASPACK_VERSION " $LASPACK_INCLUDE_PATH/version.h | sed -e "s/[^0-9.]*//g"`
+    echo "$as_me:$LINENO: result: <<< Configuring library with LASPACK version $laspack_version support >>>" >&5
+echo "${ECHO_T}<<< Configuring library with LASPACK version $laspack_version support >>>" >&6
+  else
+    enablelaspack=no
+  fi
+
+
+
+fi
+
+
+
 # Check whether --enable-petsc or --disable-petsc was given.
 if test "${enable_petsc+set}" = set; then
   enableval="$enable_petsc"
@@ -5142,7 +5144,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5145:" \
+echo "$as_me:5147:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5308,7 +5310,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5311: \"$ac_link\") >&5
+(eval echo $as_me:5313: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5387,7 +5389,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5390: \"$ac_link\") >&5
+(eval echo $as_me:5392: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6348,8 +6350,6 @@ s,@MPCXX@,$MPCXX,;t t
 s,@PWD@,$PWD,;t t
 s,@enablexdr@,$enablexdr,;t t
 s,@enablecomplex@,$enablecomplex,;t t
-s,@LASPACK_INCLUDE_PATH@,$LASPACK_INCLUDE_PATH,;t t
-s,@enablelaspack@,$enablelaspack,;t t
 s,@HDF4_INCLUDE_PATH@,$HDF4_INCLUDE_PATH,;t t
 s,@HDF4_LIB_PATH@,$HDF4_LIB_PATH,;t t
 s,@HDF4_LIB_NAMES@,$HDF4_LIB_NAMES,;t t
@@ -6368,6 +6368,8 @@ s,@enablesfc@,$enablesfc,;t t
 s,@TECPLOT_LIBRARY@,$TECPLOT_LIBRARY,;t t
 s,@TECPLOT_INCLUDE_PATH@,$TECPLOT_INCLUDE_PATH,;t t
 s,@enabletecplot@,$enabletecplot,;t t
+s,@LASPACK_INCLUDE_PATH@,$LASPACK_INCLUDE_PATH,;t t
+s,@enablelaspack@,$enablelaspack,;t t
 s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
@@ -7365,8 +7367,6 @@ s,@MPCXX@,$MPCXX,;t t
 s,@PWD@,$PWD,;t t
 s,@enablexdr@,$enablexdr,;t t
 s,@enablecomplex@,$enablecomplex,;t t
-s,@LASPACK_INCLUDE_PATH@,$LASPACK_INCLUDE_PATH,;t t
-s,@enablelaspack@,$enablelaspack,;t t
 s,@HDF4_INCLUDE_PATH@,$HDF4_INCLUDE_PATH,;t t
 s,@HDF4_LIB_PATH@,$HDF4_LIB_PATH,;t t
 s,@HDF4_LIB_NAMES@,$HDF4_LIB_NAMES,;t t
@@ -7385,6 +7385,8 @@ s,@enablesfc@,$enablesfc,;t t
 s,@TECPLOT_LIBRARY@,$TECPLOT_LIBRARY,;t t
 s,@TECPLOT_INCLUDE_PATH@,$TECPLOT_INCLUDE_PATH,;t t
 s,@enabletecplot@,$enabletecplot,;t t
+s,@LASPACK_INCLUDE_PATH@,$LASPACK_INCLUDE_PATH,;t t
+s,@enablelaspack@,$enablelaspack,;t t
 s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
