support trilinos build directories and install directories

diff --git a/libmesh/configure b/libmesh/configure
--- a/libmesh/configure
+++ b/libmesh/configure
@@ -12769,7 +12769,29 @@ fi
 
 
   if test "$withtrilinosdir" != no ; then
-    as_ac_File=`echo "ac_cv_file_$withtrilinosdir/packages/aztecoo/Makefile.export.aztecoo" | $as_tr_sh`
+    as_ac_File=`echo "ac_cv_file_$withtrilinosdir/include/Makefile.export.aztecoo" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $withtrilinosdir/include/Makefile.export.aztecoo" >&5
+echo $ECHO_N "checking for $withtrilinosdir/include/Makefile.export.aztecoo... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$withtrilinosdir/include/Makefile.export.aztecoo"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  AZTECOO_MAKEFILE_EXPORT=$withtrilinosdir/include/Makefile.export.aztecoo
+else
+  as_ac_File=`echo "ac_cv_file_$withtrilinosdir/packages/aztecoo/Makefile.export.aztecoo" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $withtrilinosdir/packages/aztecoo/Makefile.export.aztecoo" >&5
 echo $ECHO_N "checking for $withtrilinosdir/packages/aztecoo/Makefile.export.aztecoo... $ECHO_C" >&6; }
 if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -12792,6 +12814,8 @@ if test `eval echo '${'$as_ac_File'}'` = yes; then
   AZTECOO_MAKEFILE_EXPORT=$withtrilinosdir/packages/aztecoo/Makefile.export.aztecoo
 else
   enabletrilinos=no
+fi
+
 fi
 
 
