it is not sufficient to check for the existance of rpc/rpc.h and then infer XDR support.  We now check for the availability of xdrsdtio_create, which should be sufficient.

diff --git a/libmesh/configure b/libmesh/configure
--- a/libmesh/configure
+++ b/libmesh/configure
@@ -6892,7 +6892,6 @@ else
   enablexdr=yes
 fi;
 
-
 if test "$enablexdr" != no ; then
 
 for ac_header in rpc/rpc.h
@@ -7031,10 +7030,99 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
- echo "<<< Configuring library with XDR support >>>"
+
+                     echo "$as_me:$LINENO: checking for xdrstdio_create" >&5
+echo $ECHO_N "checking for xdrstdio_create... $ECHO_C" >&6
+if test "${ac_cv_func_xdrstdio_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char xdrstdio_create (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char xdrstdio_create ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_xdrstdio_create) || defined (__stub___xdrstdio_create)
+choke me
+#else
+char (*f) () = xdrstdio_create;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != xdrstdio_create;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_xdrstdio_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_func_xdrstdio_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_xdrstdio_create" >&5
+echo "${ECHO_T}$ac_cv_func_xdrstdio_create" >&6
+if test $ac_cv_func_xdrstdio_create = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_XDR 1
+_ACEOF
+
+                                     echo "<<< Configuring library with XDR support >>>"
+
+else
+  enablexdr=no
+fi
+
+
+else
+  enablexdr=no
 fi
 
 done
+
 
                # Check whether --enable-mgf-workaround or --disable-mgf-workaround was given.
 if test "${enable_mgf_workaround+set}" = set; then
@@ -7054,6 +7142,8 @@ _ACEOF
 echo "${ECHO_T}<<< Configuring library to work around broken MGF boundary conditions >>>" >&6
    fi
    fi
+
+
 
 
 
@@ -7426,7 +7516,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7429:" \
+echo "$as_me:7519:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7594,7 +7684,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7597: \"$ac_link\") >&5
+(eval echo $as_me:7687: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7674,7 +7764,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7677: \"$ac_link\") >&5
+(eval echo $as_me:7767: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
