check for strstream if sstream is not found

diff --git a/libmesh/configure b/libmesh/configure
--- a/libmesh/configure
+++ b/libmesh/configure
@@ -3538,6 +3538,89 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_SSTREAM
 _ACEOF
 
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRINGSTREAM
+_ACEOF
+
+else
+    echo "$as_me:$LINENO: checking whether the compiler has strstream" >&5
+echo $ECHO_N "checking whether the compiler has strstream... $ECHO_C" >&6
+if test "${ac_cv_cxx_have_strstream+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <strstream>
+#ifdef HAVE_NAMESPACES
+using namespace std;
+#endif
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+strstream message; message << "Hello"; return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_have_strstream=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_cxx_have_strstream=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_have_strstream" >&5
+echo "${ECHO_T}$ac_cv_cxx_have_strstream" >&6
+if test "$ac_cv_cxx_have_strstream" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRSTREAM
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRINGSTREAM
+_ACEOF
+
+fi
+
 fi
 
 
@@ -5038,7 +5121,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5041:" \
+echo "$as_me:5124:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5204,7 +5287,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5207: \"$ac_link\") >&5
+(eval echo $as_me:5290: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5283,7 +5366,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5286: \"$ac_link\") >&5
+(eval echo $as_me:5369: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
